name: Working with Environments
on:
    workflow_dispatch:
        inputs:
            target-env:
                descripcion: Entorno
                type: environment
                default: pre
run-name: "Working with Environments | env - ${{inputs.target-env.default}}"
jobs:
    echo:
        runs_on: ubuntu_latest
        environment: ${{inputs.target-env}}
        env:
            my-env-value: ${{vars.MY_ENV_VALUE}}

        steps:
            - name: Echo vars
              run: echo "Env variable ${{env.my-env-value}}"
